version: '2'
services:
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.9.3
    ports:
      - 5601:5601
    restart: always
    networks:
      - parlai_net
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml


networks:
  parlai_net:
    name: parlai_net
    driver: bridge

  elastic_net:
    name: elastic_net
    driver: bridge
